version: "3.8"
services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
      network: host
    working_dir: /usr/src/app
    volumes:
      - ./backend/sessions:/usr/src/app/sessions
      - ./backend/public:/usr/src/app/public
    environment:
      DBHOST: mongo
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    depends_on:
      - mongo
    networks:
      - backend-net
  mongo:
    container_name: mongo-container
    build:
      context: ./backend
      dockerfile: database.Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_REPLICA_HOST: $MONGO_REPLICA_HOST
      MONGO_REPLICA_PORT: $MONGO_PORT
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    expose:
      - "$MONGO_PORT"
    networks:
      - backend-net
    volumes:
      - mongovolume:/data/db
  test-db:
    container_name: test-db-container
    build:
      context: ./backend
      dockerfile: test-db.Dockerfile
    ports:
      - "$TESTDB_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_TEST_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_TEST_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_REPLICA_HOST: $MONGO_REPLICA_TEST_HOST
      MONGO_REPLICA_PORT: $MONGO_PORT
    networks:
      - backend-net
  front:
    container_name: front-container
    build:
      context: ./sublet-front
      network: host
    depends_on:
      - backend
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
networks:
  backend-net:
    driver: bridge

volumes:
  mongovolume:
